AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Task Management System - SAM backend for task creation, retrieval, and update

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: TaskTable

Resources:
  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TaskTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: taskId
          KeyType: HASH

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/createTask/app.handler
      Events:
        CreateTaskAPI:
          Type: Api
          Properties:
            Path: /tasks
            Method: post

  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/getTasks/app.handler
      Events:
        GetTasksAPI:
          Type: Api
          Properties:
            Path: /tasks
            Method: get

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/updateTask/app.handler
      Events:
        UpdateTaskAPI:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: put

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Task Management System"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks"
